{{- if .Values.conditionalEnabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-secret-conditional
spec:
  refreshInterval: "30m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: demo-secret-conditional
  dataFrom:
    -extract:
      key: secret/demo-secrets
      conversionStrategy: Default
      metadataPolicy: None
      
{{- end }}
