apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-secret
spec:
  refreshInterval: "30m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: demo-secret
  data:
  - secretKey: cert
    remoteRef:
      key: secret/demo-secrets
      property: cert
