apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns
  annotations:
    avp.kubernetes.io/path: "secret/data/cloudflare/apitoken"
  namespace: cert-manager
type: Opaque
stringData:
  api-key: <globalKey>